{% set name = "uncrustify" %}
{% set version = "0.75.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/uncrustify/uncrustify/archive/{{ name }}-{{ version }}.tar.gz
    sha256: fd14acc0a31ed88b33137bdc26d32964327488c835f885696473ef07caf2e182

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - ninja
    - cmake

test:
  commands:
    - uncrustify --version

about:
  home: http://uncrustify.sourceforge.net/
  license: GPL-2.0-only
  license_file: COPYING
  summary: |
    A source code beautifier for C, C++, C#, ObjectiveC, D, Java, Pawn and VALA

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
