{% set name = "uncrustify" %}
{% set version = "0.73.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/uncrustify/uncrustify/archive/{{ name }}-{{ version }}.tar.gz
    sha256: 2df0326ba8c413d675b796e051d89a318b7c9cccebc993d66466e2e7fd970672

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - ninja
    - cmake

test:
  commands:
    - uncrustify --version

about:
  home: http://uncrustify.sourceforge.net/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: |
    A source code beautifier for C, C++, C#, ObjectiveC, D, Java, Pawn and VALA

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
