{% set name = "uncrustify" %}
{% set version = "0.78.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/uncrustify/uncrustify/archive/{{ name }}-{{ version }}.tar.gz
    sha256: ecaf4c0adca14c36dfffa30bc28e69865115ecd602c90eb16a8cddccb41caad2

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - ninja
    - cmake

test:
  commands:
    - uncrustify --version

about:
  home: http://uncrustify.sourceforge.net/
  license: GPL-2.0-only
  license_file: COPYING
  summary: |
    A source code beautifier for C, C++, C#, ObjectiveC, D, Java, Pawn and VALA

extra:
  recipe-maintainers:
    - traversaro
    - seanyen
    - wolfv
