schema_version: 1

context:
  name: uncrustify
  version: "0.83.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/uncrustify/uncrustify/archive/${{ name }}-${{ version }}.tar.gz
    sha256: 1d4d3ab3a991c66eb24cb0a3e690573b4882fd98bc6ec64a01c283998c20dc87

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - cmake

tests:
  - script:
      - uncrustify --version

about:
  license: GPL-2.0-only
  license_file: COPYING
  summary: |
    A source code beautifier for C, C++, C#, ObjectiveC, D, Java, Pawn and VALA


  homepage: http://uncrustify.sourceforge.net/

extra:
  recipe-maintainers:
    - traversaro
    - seanyen
    - wolfv
