schema_version: 1

context:
  name: uncrustify
  version: "0.82.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/uncrustify/uncrustify/archive/${{ name }}-${{ version }}.tar.gz
    sha256: e05f8d5ee36aaa1acfa032fe97546b7be46b1f4620e7c38037f8a42e25fe676f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - cmake

tests:
  - script:
      - uncrustify --version

about:
  license: GPL-2.0-only
  license_file: COPYING
  summary: |
    A source code beautifier for C, C++, C#, ObjectiveC, D, Java, Pawn and VALA


  homepage: http://uncrustify.sourceforge.net/

extra:
  recipe-maintainers:
    - traversaro
    - seanyen
    - wolfv
